server:
  port: 7001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful
spring:
  application:
    name: select-service
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: user
#    password: 1234
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/deliveryservice?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
management:
  endpoints:
    web:
      exposure:
        include: refresh

mybatis:
  mapper-locations: classpath:mappers/*.xml

swfm:
  file-service-url: ${SELECT_SERVICE_URL:http://localhost:7013}/selectImage