server:
  port: 7001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

spring:
  datasource:
    replication:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
      write:
        name: write
        url: ${DB_MASTER_URL:jdbc:mysql://localhost:3306/deliveryservice?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}  # 마스터 DB URL
      reads:
        - name: read
          username: ${DB_SLAVE_NAME:root}
          password: 1234
          url: ${DB_SLAVE_URL:jdbc:mysql://localhost:3306/deliveryservice?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8}  # 슬레이브 DB URL

    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
management:
  endpoints:
    web:
      exposure:
        include: refresh

mybatis:
  mapper-locations: classpath:mappers/*.xml

swfm:
  file-service-url: ${SELECT_SERVICE_URL:http://localhost:7013}/selectImage

aws:
  region: ${AWS_REGION:ap-northeast-2}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket-name: img-bucket-2024
  sqs:
    queue-name: products