apiVersion: apps/v1
kind: Deployment
metadata:
  name: select-service
  labels:
    app: select-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: select-service
  template:
    metadata:
      labels:
        app: select-service
    spec:
      containers:
        - name: select-service
          image: select-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 7001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://polar-mysql:3306/deliveryservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
            - name: SPRING_PROFILES_ACTIVE
              value: testdata